version: 2
executorType: docker
jobs:
  build:
    environment:
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      - APK_FILENAME: "app-release.apk"
      - REACT_NATIVE_MAX_WORKERS: 2
    working_directory: ~/app
    docker:
      - image: entria/react-native-android
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-npm
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Relay Compiler
          command: yarn relay
      - run:
          name: Build APK
          command: |
            cd android
            chmod +x ./gradlew && ./gradlew clean && ./gradlew assembleRelease
      - save_cache:
          key: v1-npm
          paths:
            - node_modules/
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - store_artifacts:
          path: android/app/build/outputs/apk/
          destination: android
      - store_artifacts:
          path: android/app/build/reports
          destination: android
